### PR TITLE
Point SBI-rs to main again

### PR DESCRIPTION
**Pull request by glg-rv**
Joy of submodules.

Yesterday tellus PR inadvertedly changed SBI-rs off main, mostly removing FID fixes patch.

Point it back again to main.

### CODE REVIEW

**Review by mnissler-rivos — APPROVED** [review]
I find the GitHub UI confusing, but I think I managed to convince myself that it's pointing to the correct commit now.

**Comment by glg-rv** [comment]
Yeah, the only way is to look at it through the raw patch. I think from now on we need an explicit explanation in PR on why we're updating SBI-rs. And check for it. It's very easy to miss.

**Comment by dgreid** [comment]
I think this should move to 0d1037c68 instead. then the vm.rs patch isn't needed.

**Comment by dgreid** [comment]
I'll post one.

**Pull request merged**
